### ISSUE TITLE
change the number of classes

### ISSUE THREAD

**Issue by xialuxi** [daijifeng001/MNC#50]
I0325 12:54:42.795264  6120 solver.cpp:245]     Train net output #11: rpn_loss_bbox = 0.0137722 (* 1 = 0.0137722 loss)
I0325 12:54:42.795266  6120 solver.cpp:245]     Train net output #12: seg_cls_loss = 0.137927 (* 1 = 0.137927 loss)
I0325 12:54:42.795269  6120 solver.cpp:245]     Train net output #13: seg_cls_loss_ext = 0.541152 (* 1 = 0.541152 loss)
I0325 12:54:42.795272  6120 sgd_solver.cpp:106] Iteration 10, lr = 0.0001
Traceback (most recent call last):
  File "/home/dl/work/MNC/tools/train_net.py", line 97, in <module>
    _solver.train_model(args.max_iters)
  File "/home/dl/work/MNC/tools/../lib/caffeWrapper/SolverWrapper.py", line 138, in train_model
    self.snapshot()
  File "/home/dl/work/MNC/tools/../lib/caffeWrapper/SolverWrapper.py", line 92, in snapshot
    self.bbox_stds[:, np.newaxis])
ValueError: operands could not be broadcast together with shapes (84,8192) (8,1)

**Comment by xialuxi** [comment]
Could you tell me how to solver this problem?
