### ISSUE TITLE
Error in demo

### ISSUE THREAD

**Issue by jinyu121** [daijifeng001/MNC#72]
Hi~
I am running the demo, and error happens:

```
Demo for data/demo/2008_000533.jpg
forward time 0.203548
Traceback (most recent call last):
  File "./tools/demo.py", line 170, in <module>
    superimpose_image.save(superimpose_name, 'JPEG')
  File "/home/haoyu/py2/local/lib/python2.7/site-packages/PIL/Image.py", line 1928, in save
    save_handler(self, fp, filename)
  File "/home/haoyu/py2/local/lib/python2.7/site-packages/PIL/JpegImagePlugin.py", line 607, in _save
    raise IOError("cannot write mode %s as JPEG" % im.mode)
IOError: cannot write mode RGBA as JPEG
```

I have tried to add `.png` , remove `JPEG`, change `JPEG` into `PNG`, not working.

Anyone can tell me how to solve it? THX

**Comment by tuchengyuan** [comment]
According this post: https://github.com/python-pillow/Pillow/issues/2724

you can execute:

sudo pip install pillow=4.1.1
